/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author Tran Trung Nghia
 */
public class NangCao_Login extends javax.swing.JFrame {

        List<ThongTinDangNhap> lstThongTinDangNhap = new ArrayList<>();
        boolean dangNhapThanhCong = false;

        String str = "";

        /**
         * Creates new form NangCao
         */
        public NangCao_Login() {
                initComponents();
                setResizable(false);
                setLocationRelativeTo(null);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                try {
                        loadToFile();
                } catch (Exception e) {
                        e.printStackTrace();
                }

        }
        //------------------------------------------------------------------------------------------------------------------------------------------------

        public Object readObject(String path) throws Exception {
                try (FileInputStream fin = new FileInputStream(path); ObjectInputStream ois = new ObjectInputStream(fin);) {
                        Object obj = ois.readObject();
                        return obj;
                }

        }

        public void writeObject(String path, Object obj) throws Exception {
                try (
                        FileOutputStream fos = new FileOutputStream(path); ObjectOutputStream oos = new ObjectOutputStream(fos);) {
                        oos.writeObject(obj);
                }
        }

        public void saveToFile() throws Exception {
                writeObject("thongTinDangNhap_LAB3.txt", lstThongTinDangNhap);
        }

        public void loadToFile() throws Exception {
                lstThongTinDangNhap = (List<ThongTinDangNhap>) readObject("thongTinDangNhap_LAB3.txt");
        }

        //------------------------------------------------------------------------------------------------------------------------------------------------
        public void fillToForm(String id , String pass){
                txtTaiKhoan.setText(id);
                txtMatKhau.setText(pass);
        }
        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnQRCode = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnTaoTaiKhoan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG NHẬP");

        btnQRCode.setText("QR Code");
        btnQRCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQRCodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQRCodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQRCodeMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tài khoản");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mật khẩu");

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnTaoTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTaoTaiKhoan.setText("Tạo tài khoản");
        btnTaoTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaoTaiKhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTaoTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaoTaiKhoanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 101, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(btnQRCode))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatKhau)
                            .addComponent(txtTaiKhoan)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDangNhap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnTaoTaiKhoan)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnQRCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangNhap)
                    .addComponent(btnThoat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaoTaiKhoan)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void btnQRCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQRCodeMouseClicked
                // TODO add your handling code here:
                Scan_QR_CODE scanQR = new Scan_QR_CODE();
                scanQR.setVisible(true);
        }//GEN-LAST:event_btnQRCodeMouseClicked

        private void btnQRCodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQRCodeMouseEntered
                // TODO add your handling code here:
                btnQRCode.setForeground(Color.RED);
        }//GEN-LAST:event_btnQRCodeMouseEntered

        private void btnQRCodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQRCodeMouseExited
                // TODO add your handling code here:
                btnQRCode.setForeground(Color.BLACK);
        }//GEN-LAST:event_btnQRCodeMouseExited

        private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
                // TODO add your handling code here:
                if (txtTaiKhoan.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Nhập tài khoản !");
                        txtTaiKhoan.requestFocus();
                        return;
                }
                if (txtMatKhau.getPassword().length == 0) {
                        JOptionPane.showMessageDialog(this, "Nhập mật khẩu");
                        txtMatKhau.requestFocus();
                        return;
                }
                boolean tonTai = false;
                String mk = new String(txtMatKhau.getPassword());
                for (int i = 0; i < lstThongTinDangNhap.size(); i++) {
                        if (lstThongTinDangNhap.get(i).getId().equals(txtTaiKhoan.getText()) && lstThongTinDangNhap.get(i).getPassword().equals(mk)) {
                                tonTai = true;
                                break;
                        }
                }
                if (tonTai) {
                        JOptionPane.showMessageDialog(this, "Đăng nhập thành công !");
                        Bai2 b2  = new Bai2();
                        b2.setVisible(true);
                        this.dispose();
                }else{
                        JOptionPane.showMessageDialog(this, "Đăng nhập thất bại");
                }

        }//GEN-LAST:event_btnDangNhapActionPerformed

        private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
                // TODO add your handling code here:
                System.exit(0);
        }//GEN-LAST:event_btnThoatActionPerformed

        private void btnTaoTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoTaiKhoanMouseClicked
                // TODO add your handling code here:
                NangCao_Regis nc = new NangCao_Regis();
                nc.setVisible(true);
                this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                this.setVisible(false);
        }//GEN-LAST:event_btnTaoTaiKhoanMouseClicked

        private void btnTaoTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoTaiKhoanMouseEntered
                // TODO add your handling code here:
                btnTaoTaiKhoan.setForeground(Color.RED);
        }//GEN-LAST:event_btnTaoTaiKhoanMouseEntered

        private void btnTaoTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoTaiKhoanMouseExited
                // TODO add your handling code here:
                btnTaoTaiKhoan.setForeground(Color.BLACK);
        }//GEN-LAST:event_btnTaoTaiKhoanMouseExited

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(NangCao_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(NangCao_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(NangCao_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(NangCao_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new NangCao_Login().setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel btnQRCode;
    private javax.swing.JLabel btnTaoTaiKhoan;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
